services:
    sonata.admin.posts:
        class: AppBundle\Admin\PostsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Posts" }
        arguments:
            - ~
            - AppBundle\Entity\Posts
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]